### ISSUE TITLE
ZIO2 performance issue while performing streaming calls on version `0.6.x`

### ISSUE THREAD

**Issue by cipriansofronia** [scalapb/zio-grpc#513] opened 2023-06-15 13:31 UTC
We recently migrated to ZIO2, so zio-grpc got bumped to `0.6.0-rc5`. We've noticed some performance issues after the upgrade while performing streaming calls. Going to attach some screenshots of the IntelliJ Profiler. 

On the upper hand of the screenshot there is the timeline of the previous version of zio-grpc (`0.5.1`) running with ZIO1 and below we have the zio-grpc version `0.6.0-rc5` with ZIO2. 
The streaming request is kept alive for a few seconds for both versions but we can notice some differences between these two. On `0.5` there is a small spike when the request is triggered but then the CPU goes down and it stays like that, on `0.6` the CPU load is bigger and it says like that for the duration of the streaming request (not shown here in the screenshots but if we trigger more requests then the CPU goes even higher). 
There are no other changes in our service, only the migration to ZIO2 and bumping zio-grpc, so not doing anything extra on the new version for the same streaming call. The only thing different I noticed is that `0.6` is allocating more resources while performing `serverStreamingWithBackpressure` and underneath is calling ZIO2 internals. Using ZIO2 streaming so far in other parts of the app did not present performance issues.

<img width="3004" alt="Screenshot 2023-06-15 at 08 17 42" src="https://github.com/scalapb/zio-grpc/assets/9365666/d476e5a0-0d83-4495-8c67-f0201cdc6276">
<img width="3006" alt="Screenshot 2023-06-15 at 08 16 18" src="https://github.com/scalapb/zio-grpc/assets/9365666/375f6621-70ed-4d0d-8426-dac3c8a2dc18">

We isolated even more the streaming call, we created a separate project with zio-grpc `0.6` where we only do:
```scala
ZStream(<zio_grpc_generated_class>.defaultInstance)
      .repeat(Schedule.spaced(10.second))
```
So, nothing CPU consuming and we got the same behaviour. 

Please advise if more informations are needed.

**Comment by regiskuckaertz** [comment] 2023-06-16 05:54
Have you tried increasing the back pressure queue size? The default is very small and that may explain this behaviour. We use a queue of 512k iirc in our service.

**Comment by cipriansofronia** [comment] 2023-06-16 06:59
No, I did not, will give it a try! Thanks! 🙌🏻

**Comment by Gregory-Berkman-Imprivata** [comment] 2023-06-16 20:19
We are running into a very similar performance problem. We are not using streaming but we notice that when we receive grpc requests over time, the number of `FiberId$Runtime` instances continuously increases and never drops. Eventually performance degrades significantly and Kubernetes kills the node. 
For unary requests we can see that a `forkDaemon` is being called (also called for streaming requests) here: 
https://github.com/scalapb/zio-grpc/blob/4c20b9b9fcd7b68201cdbb7654c7b60dddd25d3e/core/src/main/scalajvm/scalapb/zio_grpc/server/ListenerDriver.scala#L38
Is the new fiber correctly being released?

**Comment by regiskuckaertz** [comment] 2023-06-17 07:22
@cipriansofronia hello - could you give this one a try: https://github.com/scalapb/zio-grpc/pull/514 It maybe was a mistake to use `toQueueOfElements`, but I also wonder if calling `isReady` that much is contributing to it. The grpc-java internal buffer is currently fixed at 32kb so it may kick in very often depending on the workload. Another road to explore would be to use the stream observer instead, I'll look into that later. See https://github.com/grpc/grpc-java/issues/5433

@Gregory-Berkman-Imprivata that looks like a separate issue but you are right that we should rather fork in a scope that is closed when the call terminates.

**Comment by cipriansofronia** [comment] 2023-06-17 07:23
@regiskuckaertz, I published locally your changes from #514, tested it with the `helloworld` example and I can tell that this version does not stress the CPU anymore, there is a small spike at first when the request is made but then it drops down to almost 0 while the request is still active and the stream is emitting elements. I tried performing multiple requests in the same time and the CPU stayed the same. It performs well even with the default queue size of 16. Thank you for looking into it! 🙏🏻 
<img width="1840" alt="Screenshot 2023-06-17 at 10 21 35" src="https://github.com/scalapb/zio-grpc/assets/9365666/7bdfb9ca-ba77-4b09-b5f1-6713fc3dc4b0">
<img width="1840" alt="Screenshot 2023-06-17 at 10 21 49" src="https://github.com/scalapb/zio-grpc/assets/9365666/f8bfe19d-b395-40ad-bcfc-53c630ff21ee">

**Comment by regiskuckaertz** [comment] 2023-06-17 07:28
Yiihaaa! That is great to hear, thanks for trying it out. It's also weird to come back to something you wrote months ago and think "wow was I on the crack pipe back then? this is way too complex" 😄

**Comment by regiskuckaertz** [comment] 2023-06-17 17:10
@Gregory-Berkman-Imprivata I think this will help #515

**Comment by cipriansofronia** [comment] 2023-06-19 05:55
@thesamet thank you for merging these PRs, unfortunately there is an issue publishing the [snapshots](https://github.com/scalapb/zio-grpc/actions/runs/5307856319/jobs/9606770350) it appears.

**Comment by cipriansofronia** [comment] 2023-06-19 12:16
@thesamet, could you release another RC with these changes, please?

**Comment by thesamet** [comment] 2023-06-20 18:34
Sure, will cut a release this week.

**Comment by cipriansofronia** [comment] 2023-06-21 06:46
@regiskuckaertz and @thesamet, I really appreciate your help and fast replies. The issue is solved now, so I'm closing it. Cheers!

**Comment by ghostdogpr** [comment] 2023-06-28 07:33
We did a round of load testing using RC5 (which reproduced this issue, perf was bad) and then using the latest snapshot, and the latest shapshot gave us a great performance (better than our zio 1 code!). How about a first official release for ZIO 2 finally? 😄

**Comment by Gregory-Berkman-Imprivata** [comment] 2023-07-28 19:56
I am still seeing 

> We are running into a very similar performance problem. We are not using streaming but we notice that when we receive grpc requests over time, the number of `FiberId$Runtime` instances continuously increases and never drops. Eventually performance degrades significantly and Kubernetes kills the node. For unary requests we can see that a `forkDaemon` is being called (also called for streaming requests) here:
> 
> https://github.com/scalapb/zio-grpc/blob/4c20b9b9fcd7b68201cdbb7654c7b60dddd25d3e/core/src/main/scalajvm/scalapb/zio_grpc/server/ListenerDriver.scala#L38
> 
> 
> Is the new fiber correctly being released?

@regiskuckaertz  Not sure if this has been fixed actually. I can open a new issue for this but I am still seeing the number of `FiberId$Runtime` increasing continuously.

**Comment by ghostdogpr** [comment] 2023-08-01 02:20
I think you can close this issue since this is unrelated to streaming. Let's discuss in https://github.com/scalapb/zio-grpc/issues/537

**Closed** 2023-08-01 02:21 UTC
